import { Suspense } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Canvas } from "@react-three/fiber";
import { OrbitControls, Stage } from "@react-three/drei";
import BoxMesh from "../components/BoxMesh";
import SphereMesh from "../components/SphereMesh";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Canvas>
        <OrbitControls makeDefault autoRotate />
        <Suspense fallback={null}>
          <Stage preset="rembrandt">
            <BoxMesh />
            <SphereMesh position={[2, 0, 0]} />
          </Stage>
        </Suspense>
      </Canvas>
    </div>
  );
};

export default Home;
